using System;
using System.ComponentModel.DataAnnotations;

namespace Expence_Tracker
{
    /// <summary>
    /// Represents a single expense entry with properties for Id, Title, Amount, Date, Category, and Notes.
    /// expence class is used to store and manage individual expense records in the application.
    /// </summary>
    public class Expence
    {
        /// <summary>
        /// Gets or sets the unique identifier for the expense.
        /// This value is typically generated by the data store.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the title or short description of the expense.
        /// This property is required and should be a non-empty string.
        /// </summary>
        [Required]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the monetary amount of the expense.
        /// Must be a non-negative decimal value.
        /// </summary>
        [Required]
        [Range(0, double.MaxValue)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets the date when the expense occurred.
        /// This property is required and should represent the local date/time of the expense.
        /// </summary>
        [Required]
        public DateTime Date { get; set; }

        /// <summary>
        /// Gets or sets the category of the expense (for example, "Food", "Transport", "Utilities").
        /// This property is optional and may be null if no category is assigned.
        /// </summary>
        public string? Category { get; set; }

        /// <summary>
        /// Gets or sets optional notes or additional details about the expense.
        /// This property is optional and may contain free-form text.
        /// </summary>
        public string? Notes { get; set; }
    }

    namespace Expence_Tracker
    {
        /// <summary>
        /// Represents a category for expenses, such as "Food", "Transport", or "Utilities".
        /// Categories group multiple <see cref="Expence"/> entries.
        /// </summary>
        public class Category
        {
            /// <summary>
            /// Gets or sets the unique identifier for the category.
            /// This value is typically generated by the data store.
            /// </summary>
            [Key]
            public int Id { get; set; }

            /// <summary>
            /// Gets or sets the name of the category.
            /// This property is required and should be a non-empty string.
            /// </summary>
            [Required]
            public string Name { get; set; } = string.Empty;

            /// <summary>
            /// Gets or sets the collection of expenses associated with this category.
            /// Initialized to an empty list to prevent null reference issues.
            /// </summary>
            public ICollection<Expence> Expences { get; set; } = new List<Expence>();
        }
    }
}
